
   "source": [
    "import pandas as pd\n",
    "#change display settings\n",
    "pd.set_option('display.max_columns', 25)\n",
    "pd.set_option('display.max_rows', 500)\n",
    "\n",
    "#load sites into dataframe\n",
    "sites_2018 = pd.read_csv('sites2018_cleaned.csv', index_col='Site Name')\n",
    "sites_2019 = pd.read_csv('sites2019_cleaned_copy.csv', index_col='Site Name')\n",
    "\n",
    "#drop columns with all NaN values\n",
    "sites_2018 = sites_2018.dropna(axis=1, how='all')\n",
    "sites_2019 = sites_2019.dropna(axis=0, how='all')\n",
    "\n",
    "#iterate through all cells using index and column headers to convert string values to numeric\n",
    "\n",
    "##2018\n",
    "column_headers2018 = list(sites_2018.columns.values)\n",
    "for idx in sites_2018.index:\n",
    "    for i in column_headers2018:\n",
    "        value = sites_2018.at[idx,i]\n",
    "        if value == '<10':\n",
    "            value = 10\n",
    "        if value == '>24196':\n",
    "            value = 24196\n",
    "        int (value)\n",
    "        sites_2018.at[idx,i] = value\n",
    "\n",
    "##2019\n",
    "\n",
    "column_headers2019 = list(sites_2019.columns.values)\n",
    "for idx in sites_2019.index:\n",
    "    for i in column_headers2019:\n",
    "        value = sites_2019.at[idx,i]\n",
    "        if value == '<10':\n",
    "            value = 10\n",
    "        if value == '>24196':\n",
    "            value = 24196\n",
    "        int (value)\n",
    "        sites_2019.at[idx,i] = value\n",
    "\n",
    "#set data types\n",
    "sites_2018 = sites_2018.astype('int32')\n",
    "sites_2019 = sites_2019.astype('int32')\n",
    "\n",
    "#merge sites\n",
    "merged_df = sites_2018.append(sites_2019)\n",
    "#dropna rows\n",
    "merged_df = merged_df.dropna(axis=0, how='all')\n",
    "#dropna columns\n",
    "merged_df = merged_df.dropna(axis=1, how='any')\n",
    "\n",
    "#data type\n",
    "merged_df = merged_df.astype('int32')\n",
    "\n",
    "#descripitive stats\n",
    "print (merged_df.describe())\n",
    "\n",
    "###sites_2018[column_headers[1:len(column_headers)]] = sites[column_headers[1:len(column_headers)]].apply(pd.to_numeric)\n",
    "# #column_headers = list(sites.columns.values)\n",
    "# #print (column_headers[1:len(column_headers)])\n",
    "\n",
    "\n",
    "\n",
    "# for idx in sites.index:\n",
    "#     for i in column_headers:\n",
    "#         value = sites.at[idx,i]\n",
    "#         if value == '<10':\n",
    "#             value = 10\n",
    "#         if value == '>24196':\n",
    "#             value = 24196\n",
    "#         float (value)\n",
    "#         sites.at[idx,i] = value\n",
    "# sites[column_headers[1:len(column_headers)]] = sites[column_headers[1:len(column_headers)]].apply(pd.to_numeric)"
   ]
  },
  
